all:
  hosts:
    node1:
      ansible_host: 10.132.0.21
      ip: 10.132.0.21
      access_ip: 10.132.0.21
    node2:
      ansible_host: 10.132.0.22
      ip: 10.132.0.22
      access_ip: 10.132.0.22
    node3:
      ansible_host: 10.132.0.23
      ip: 10.132.0.23
      access_ip: 10.132.0.23
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
